### ISSUE TITLE
 'NoneType' object has no attribute 'group_add'

### ISSUE THREAD

**Issue by namantam1** [namantam1/channels-easy#4]
```bash
Exception inside application: 'NoneType' object has no attribute 'group_add'
Traceback (most recent call last):
  File "C:\Users\Naman Tamrakar\Desktop\channels-easy\example\.venv\lib\site-packages\channels\staticfiles.py", line 44, in __call__
    return await self.application(scope, receive, send)
  File "C:\Users\Naman Tamrakar\Desktop\channels-easy\example\.venv\lib\site-packages\channels\routing.py", line 71, in __call__
    return await application(scope, receive, send)
  File "C:\Users\Naman Tamrakar\Desktop\channels-easy\example\.venv\lib\site-packages\channels\sessions.py", line 47, in __call__
    return await self.inner(dict(scope, cookies=cookies), receive, send)
  File "C:\Users\Naman Tamrakar\Desktop\channels-easy\example\.venv\lib\site-packages\channels\sessions.py", line 263, in __call__
    return await self.inner(wrapper.scope, receive, wrapper.send)
  File "C:\Users\Naman Tamrakar\Desktop\channels-easy\example\.venv\lib\site-packages\channels\auth.py", line 185, in __call__
    return await super().__call__(scope, receive, send)
  File "C:\Users\Naman Tamrakar\Desktop\channels-easy\example\.venv\lib\site-packages\channels\middleware.py", line 26, in __call__
    return await self.inner(scope, receive, send)
  File "C:\Users\Naman Tamrakar\Desktop\channels-easy\example\.venv\lib\site-packages\channels\routing.py", line 150, in __call__
    return await application(
  File "C:\Users\Naman Tamrakar\Desktop\channels-easy\example\.venv\lib\site-packages\channels\consumer.py", line 94, in app
    return await consumer(scope, receive, send)
  File "C:\Users\Naman Tamrakar\Desktop\channels-easy\example\.venv\lib\site-packages\channels\consumer.py", line 62, in __call__
    await await_many_dispatch([receive], self.dispatch)
  File "C:\Users\Naman Tamrakar\Desktop\channels-easy\example\.venv\lib\site-packages\channels\utils.py", line 51, in await_many_dispatch
    await dispatch(result)
  File "C:\Users\Naman Tamrakar\Desktop\channels-easy\example\.venv\lib\site-packages\channels\consumer.py", line 73, in dispatch
    await handler(message)
  File "C:\Users\Naman Tamrakar\Desktop\channels-easy\example\.venv\lib\site-packages\channels\generic\websocket.py", line 173, in websocket_connect
    await self.connect()
  File "C:\Users\Naman Tamrakar\Desktop\channels-easy\example\channels_app\consumers.py", line 7, in connect
    await self.join("room1")
  File "C:\Users\Naman Tamrakar\Desktop\channels-easy\example\.venv\lib\site-packages\channels_easy\generic.py", line 75, in join
    await self.channel_layer.group_add(_room, self.channel_name)
AttributeError: 'NoneType' object has no attribute 'group_add'
WebSocket DISCONNECT /ws/test/ [127.0.0.1:9867]
```

**Comment by namantam1** [comment]
This issue comes when we do not specify `CHANNEL_LAYERS` in `settings.py`. Visit channels docs for more info.

For channels-easy >=v0.2.2 It throws a warning with proper message
